### ISSUE TITLE
Not functioning?

### ISSUE THREAD

**Issue by fayep** [flochtililoch/homebridge-misfit-bolt#5]
Hi,
I tried installing this on my otherwise working homebridge install.  I have tested my python bolt script and that's working... but whilst I get notifications that it is changing state and brightness, it doesn't.

```
    this.log(`Get Bolt#${this.id} ${property}`);
```

The ${} replace the previous #{} :)

**Comment by flochtililoch** [comment]
Ok, I think I forgot to have to make a few updates to the README.
I've changed that plugin to not communicate directly with `misfit-bolt` module, but instead to send HTTP requests that `misfit-bolt-http` can receive and send to the bolt through `misfit-bolt` module.
I should add some handling to log errors when HTTP requests fail.
To get this working:
- run https://github.com/flochtililoch/misfit-bolt-http
- configure your homebridge to have something that reads (assuming you're running `misfit-bolt-http` on the same host as homebridge, on the default port:

``` json
 {
    "platform": "MisfitBolt",
    "name": "MisfitBolt",
    "accessories": [{
      "id": "<your_bolt_uuid_here>",
      "name": "Bolt",
      "baseUrl": "http://localhost:3000/<your_bolt_uuid_here>"
    }]
},
```

then restart homebridge. Let me know if that helps!
PS: Thanks for your original Python script that largely contributed creating `misfit-bolt` module!
